# permissions to do viewer objectstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: objectstore-viewer-role
rules:
- apiGroups:
  - monitoring.banzaicloud.io
  resources:
  - objectstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.banzaicloud.io
  resources:
  - objectstores/status
  verbs:
  - get
